### ISSUE TITLE
C3D feature conversion to HDF5 format

### ISSUE THREAD

**Issue by jinwchoi** [cabaf/sparseprop#1]
Hi Fabian,

I'm trying to train SparseProp with your code on ActivityNet, I have some questions about C3D feature conversion to HDF5 format. 

1) What kind of C3D feature do you use for SparseProp?
2) How did you convert C3D feature files to HDF5 format? If you have script for this, can you share it? It would be really helpful for me. Thanks!

**Comment by cabaf** [comment]
Hi Jinwoo,

Sorry for being late to reply.

1) We use the publicly available pre-trained (Sports1M) C3D model which has a temporal resolution of 16 frames. Furthermore, we reduce the dimensionality of the activations of fc7 from 4096 to 500 dimensions using PCA.

2) We save a Group for each video and one Dataset with C3D features on each group. The name of each Group corresponds to the video-id, while the name used for Dataset is "c3d-features". You can find more details about HDF5 [here](https://support.hdfgroup.org/HDF5/Tutor/HDF5Intro.pdf). Additionally, you may find useful the [C3D features](http://activity-net.org/challenges/2016/download.html#c3d) provided for the [ActivityNet Challenge](http://activity-net.org/challenges/2016/).

I hope this helps you to move forward.
