### ISSUE TITLE
About train data C3D features

### ISSUE THREAD

**Issue by hayato8059** [cabaf/sparseprop#2]
hi,
Thank you for share this code. I'm study action detection, and I have the pleasure of reading this paper. 
 I extract C3D features in TH14 train data‘s 20 classes that can use in action detection. Then I want to use PCA to reduct dimension to 500 dimension. I use matlab to compute PCA, but out of memory. Our sever memory not enough. In this code, demo_c3d.hdf5 in data is  500 dimensionality. What dimension reduction method do you use?  If it is PCA, can I obtain the projection space?
Thank you.
liu.

**Comment by cabaf** [comment]
Hi Liu,

We use PCA to reduce the dimensionality. You can follow the nice [out-of-core implementation](https://gist.github.com/escorciav/e4125c7a8a2e52ab4c47) of @escorciav to obtain the PCA model without fitting all the data in memory.

**Comment by hayato8059** [comment]
I got it, thank you very much.

**Comment by escorciav** [comment]
@hayato8059, you can find the [eigendecomposition](https://github.com/escorciav/daps/tree/master/data/models#pca_c3d_fc7_thumos14hdf5) of C3D features for THUMOS14 in our [DAPs project repo](https://github.com/escorciav/daps). I hope to save you some time 😉
