### ISSUE TITLE
Error in the Demo

### ISSUE THREAD

**Issue by fizamurtaza** [cabaf/sparseprop#3]
Hello

I want to run demo using this command line
python retrieve_proposals.py data/demo_input.csv data/demo_c3d.hdf5 data/class_induced_thumos14.pkl data/demo_proposals.csv

But I am getting following error
![error](https://cloud.githubusercontent.com/assets/25634081/22731545/d59ea404-ee0c-11e6-942b-85e8eac74169.PNG)

Although I have installed all the dependencies (as far as I know) which you mentioned in description but still I don't know how to solve this problem. Also I am new in Python and I am facing problem in understanding the error.
Kindly help me to remove this error.

Thanks in advance
Fiza Murtaza

**Comment by cabaf** [comment]
Hi Fiza,

Thanks for your interest in our work.

Unfortunately the traced error is not much informative due to the crash occurred inside a Parallel job. Try to reproduce the error in sequential mode: set `n_jobs` to `1` in [this line](https://github.com/cabaf/sparseprop/blob/master/sparseprop/retrieve.py#L108) and report back if the error persists.

**Comment by fizamurtaza** [comment]
Thank you for your kind reply.
Following error I got after setting n_jobs to 1 in https://github.com/cabaf/sparseprop/blob/master/sparseprop/retrieve.py#L108

![image](https://cloud.githubusercontent.com/assets/25634081/22813159/2baf2a12-ef6b-11e6-80dd-8ce70b5ba30c.png)

**Comment by cabaf** [comment]
Thanks for reporting back. It seems SPAMs does not support the parameter `linesearch_mode` on windows. You can remove that key from the parameters dictionary: after [this line](https://github.com/cabaf/sparseprop/blob/master/sparseprop/retrieve.py#L100) write `del params['linesearch_mode']`. Let us know if it solves the problem.

**Comment by fizamurtaza** [comment]
Thank you so much Fabian 👍 
Yes byy writing 
del params['linesearch_mode']  after line https://github.com/cabaf/sparseprop/blob/master/sparseprop/retrieve.py#L100
solved the problem Thanks God :)

How I can learn coding in Python? Can you send me the tutorial links from where I can learn from very start??
Also Why you preferred Python over Matlab?
