### ISSUE TITLE
A problem about utils.py

### ISSUE THREAD

**Issue by hayato8059** [cabaf/sparseprop#5]
Hi,
When I try to train a new model, an error occurred. Line 23 in utils.py in function get_typical_durations().  df.shape[0], but df is not defined. Is this df same as df in run_train.py, or have some other meaning?
Thank you.
Liu.

**Comment by cabaf** [comment]
Hey Liu, thanks for reporting! I have fixed the bug in [this commit](https://github.com/cabaf/sparseprop/commit/1731cc97edf761f6b7d889860845525824ea57d2).
