### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by fizamurtaza** [cabaf/sparseprop#6]
Hello Caba,

You have mentioned that you have used C3D features but in paper you mentioned that you have used encoding of each STIP point using HOG and HOF I am confused :(
Can you help me understanding this that what feature representation you have actually used?

**Comment by cabaf** [comment]
In our CVPR16 paper, we use STIPs as our video representation. However, we found out after the paper Submission deadline that C3D features provide a boost in performance (both speed and accuracy). The code is agnostic on the type of feature used. You only need to format your data in a similar way to [this](https://github.com/cabaf/sparseprop/blob/master/sparseprop/feature.py).

**Comment by fizamurtaza** [comment]
Okay...
Thank you so much for reply.
